#!/bin/sh

export DWL_HELPER_DIR=${DWL_HELPER_DIR:-/usr/lib/dwl-personal}
export PATH="$DWL_HELPER_DIR:$PATH"
export GTK_THEME=Wallust-Dark
export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORM='wayland;xcb'
exec dwl -s "$DWL_HELPER_DIR/dwl-startup"
